### PR TITLE
Set sonar.delphi.installationPath when initializing SonarDelphi

### LINKED ISSUE #10: DelphiLint fails when Delphi 11 is not installed
### Prerequisites

- [X] This bug is in DelphiLint, not SonarDelphi, SonarQube, or my Delphi code.
- [X] This bug has not already been reported.

### Delphi IDE version

12 Athens

### DelphiLint version

1.0 Latest release

### SonarDelphi version

1.3.0 default version

### SonarQube version

_No response_

### Issue description

image
I have multiple delphi versions installed and I just 
- ran the install.bat, 
- opened a random project and 
- tried to run it, 
- error happens. 

I have PATH overrides on Delphi IDE since its mandatory when you have multiple versions installed. Maybe DL isn't reading from that but is reading from windows' Path instead.

### Steps to reproduce

- ran the install.bat, 
- opened a random project and 
- tried to run it, 
- error happens. 

### Minimal Delphi code exhibiting the issue

_No response_

### PR DESCRIPTION
**Pull request by fourls**
Fixes #10 by using the correct setting name for the SonarDelphi property containing Delphi installation.

DelphiLint currently incorrectly passes the Delphi installation through to SonarDelphi using the `sonar.delphi.bds.path` setting, which was replaced by `sonar.delphi.installationPath` in [SonarDelphi 1.0.0](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.0.0). As a result, SonarDelphi uses the default Delphi 11 installation path in all cases, which causes errors when Delphi 11 is not installed.

### CODE REVIEW

File: server/delphilint-server/src/main/java/au/com/integradev/delphilint/analysis/EngineStartupConfiguration.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ public Set<Path> getPluginPaths() {
 
   public Map<String, String> getBaseProperties() {
     return Map.of(
-        "sonar.delphi.bds.path", bdsPath,
+        "sonar.delphi.installationPath", bdsPath,
         "sonar.delphi.compiler.version", compilerVersion);
```
Comment (Cirras) [inline server/delphilint-server/src/main/java/au/com/integradev/delphilint/analysis/EngineStartupConfiguration.java:42]: The `sonar.delphi.compiler.version` property was also renamed to `sonar.delphi.compilerVersion` in SonarDelphi v1.0.0.

**Review by Cirras — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -7,6 +7,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
+### Fixed
+
+* DelphiLint now passes SonarDelphi the correct Delphi installation and compiler version when running in Delphi 12.
```
Comment (Cirras) [inline CHANGELOG.md:12]:
```suggestion
* DelphiLint now passes SonarDelphi the correct Delphi installation path and compiler version when running in Delphi 12.
```

**Review by Cirras — CHANGES_REQUESTED** [review]
Looks good, one changelog tweak.

**Review by Cirras — APPROVED** [review]
Looks good to me.
