### PR TITLE
Fix blank Edge browser embeds

### LINKED ISSUE #45: Embedded browser not rendering
### Prerequisites

- [X] This bug is in DelphiLint, not SonarQube or the Delphi IDE.
- [X] This bug has not already been reported.
- [X] This bug is not a problem related to analysis quality (e.g. parsing errors, false positive issues), which should be raised on the [SonarDelphi repository](https://github.com/integrated-application-development/sonar-delphi/issues).

### Delphi IDE version

Various editions - Observed on Delphi 11.3 CE and Delphi 12.1

### DelphiLint version

1.1.0

### SonarDelphi version

1.6.0

### SonarQube version

_No response_

### Issue description

See discussion on #44 - embedded browser is always plain white, with no rule description rendering.

From initial testing this appears to be an issue with finding the `WebView2Loader.dll` from PATH.

### Steps to reproduce

Unclear.

### Minimal Delphi code exhibiting the issue

_No response_

### LINKED ISSUE #46: Embedded browser does not display when docked if first opened in undocked mode
### Prerequisites

- [X] This bug is in DelphiLint, not SonarQube or the Delphi IDE.
- [X] This bug has not already been reported.
- [X] This bug is not a problem related to analysis quality (e.g. parsing errors, false positive issues), which should be raised on the [SonarDelphi repository](https://github.com/integrated-application-development/sonar-delphi/issues).

### Delphi IDE version

Repro'd on Delphi 11.2 Professional and Delphi 12.1 Patch 1 Professional

### DelphiLint version

1.1.0

### SonarDelphi version

1.6.0

### SonarQube version

_No response_

### Issue description

In some circumstances the embedded Edge browser view used for rule descriptions does not render when the DelphiLint window is docked (see exact steps to reproduce below). This appears to be a visual bug rather than the result of a web view failure, since the view rerenders fine if the view is undocked and reflects changes that have been made to it while it was blank (e.g. navigating to new pages). 

When undocked:
image

When docked:
image

### Steps to reproduce

1. Load DelphiLint
2. Open the DelphiLint window via DelphiLint > Show DelphiLint **and keep undocked**
3. Click Analyze on a file that will have issues, and wait for those issues to turn up
4. Click on an issue - the rule description view will show up correctly
5. Dock the DelphiLint window - the rule description view will now be rendered as plain white

This is reproducible after this - when undocked, the view will work fine, but when docked it will display as white. 

### Minimal Delphi code exhibiting the issue

_No response_

### PR DESCRIPTION
**Pull request by fourls**
This PR fixes two separate problems that were causing the Edge browser embed to fail to display in some situations.

* The path to the Edge DLL is now added to the process PATH when the plugin is loaded, rather than by the installer. This fixes cases in which the PATH would not be fully interpreted if it was more than 2047 characters, causing the DLL to be missed.
* The web view is now reinitialized on DelphiLint form resize. This fixes #46.
  * For whatever reason, most of the events on the DelphiLint frame don't seem to get called. This is one of the few events that is reliably called when the form is docked.

Should also fix #45

### CODE REVIEW

File: client/source/DelphiLint.ToolFrame.pas [hunk 1]
```diff
@@ -568,7 +573,7 @@ function TLintToolFrame.GetIssueMetadataText(Issue: ILiveIssue): string;
       CreationDateTime := ISO8601ToDate(Issue.CreationDate, False);
       TimeSinceCreation := TTimeSpan.Subtract(Now, CreationDateTime);
 
-      ExtraInfo := Format('%s � %s � %s', [
+      ExtraInfo := Format('%s • %s • %s', [
```
Comment (zaneduffield) [inline client/source/DelphiLint.ToolFrame.pas]: The encoding appears to have changed here.

Comment (zaneduffield) [reply client/source/DelphiLint.ToolFrame.pas]: Oh, it looks like it was changed back in the next commit. I haven't pulled the code locally, so I may be mistaken.

Comment (fourls) [reply client/source/DelphiLint.ToolFrame.pas]: Why does this keep happening?? I committed all these commits at the same time, I don't know how it could have been changed.

I wonder if it's VS Code's "Stage Selected Ranges" doing something weird.

Comment (Cirras) [reply client/source/DelphiLint.ToolFrame.pas]: Time to migrate this project's source files to UTF-8, I think!

Comment (zaneduffield) [reply client/source/DelphiLint.ToolFrame.pas]: > I wonder if it's VS Code's "Stage Selected Ranges" doing something weird.

It definitely does have encoding bugs. I've encountered that before.

File: client/source/DelphiLint.ToolFrame.pas [hunk 2]
```diff
@@ -712,9 +717,24 @@ procedure TLintToolFrame.RuleBrowserCreateWebViewCompleted(Sender: TCustomEdgeBr
   DelphiColor: Integer;
 begin
   if not RuleBrowser.WebViewCreated then begin
+    Log.Warn('Rule browser could not be initialized - result code %x', [AResult]);
+    TaskMessageDlg(
+      'DelphiLint''s embedded Edge view could not be initialized.',
+      Format(
+        '(Error code %x)'#13#10'Please ensure that Microsoft Edge 79.0.309 or above is installed and ' +
+        'WebView2Loader.dll is on PATH.',
```
Comment (Cirras) [inline client/source/DelphiLint.ToolFrame.pas:729]: You handle this yourself now (previous commit), so there's nothing the user can really do about whether the dll is on PATH.
Alternatively, you could tell them to make sure the dll exists at `%APPDATA%/DelphiLint/bin`?

File: client/source/DelphiLint.Plugin.pas [hunk 3]
```diff
@@ -303,7 +304,12 @@ constructor TPluginCore.Create(Owner: TComponent; IDEServices: IIDEServices);
 //______________________________________________________________________________________________________________________
 
 procedure TPluginCore.OnRegister;
+var
+  NewPath: string;
 begin
+  NewPath := TPath.Combine(LintContext.Settings.SettingsDirectory, 'bin') + ';' + GetEnvironmentVariable('PATH');
+  SetEnvironmentVariable(PWideChar('PATH'), PWideChar(NewPath));
```
Comment (Cirras) [inline client/source/DelphiLint.Plugin.pas:311]: With this change, I think we should also adjust the install script to not change the PATH anymore.

**Review by Cirras — CHANGES_REQUESTED** [review]
Looks good! A couple of notes.

File: client/source/DelphiLint.Plugin.pas (hunk 3 above)
Comment (fourls) [reply client/source/DelphiLint.Plugin.pas:311]: I was considering it. I want to make sure that this works correctly in all cases before removing it from the install script, since if it doesn't work all the time then there's nothing the user can do. It doesn't do any active harm being paranoid and adding it to the PATH.

I'll probably improve the install script soon to have it download the default SonarDelphi version - someone suggested it on DelphiPraxis and I thought it was a good idea - so I could probably bundle the removal up with those changes. What do you think?

File: client/source/DelphiLint.ToolFrame.pas (hunk 2 above)
Comment (fourls) [reply client/source/DelphiLint.ToolFrame.pas:729]: image

How's this?

File: client/source/DelphiLint.Plugin.pas (hunk 3 above)
Comment (Cirras) [reply client/source/DelphiLint.Plugin.pas:311]: You're right that it doesn't do any active *harm*, but I don't see how we'll ever be any **more** confident that we can remove the PATH manipulation from the installer.

Comment (fourls) [reply client/source/DelphiLint.Plugin.pas:311]: Sure.

Comment (fourls) [reply client/source/DelphiLint.Plugin.pas:311]: I've removed the path configuration from the install script now.

**Review by Cirras — APPROVED** [review]
Looks good!
